### ISSUE TITLE
Bank details not being saved.

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/uc_bank_transfer#1] opened 2022-11-21 10:39 UTC
/admin/store/settings/payment/method/bank_transfer

When entering bank details, the new details are not saved.

**Comment by argiepiano** [comment] 2022-11-21 18:34
Hmm... not able to reproduce. It's saving correctly for me. Can you tell me a bit more about your set up? Was this a new installation of Ubercart?

**Comment by albanycomputers** [comment] 2022-11-21 18:50
No...  It is up to date..  I'll have a play on a test site... I'll let you know if I can replicate it.

Thanks.

**Comment by albanycomputers** [comment] 2022-11-21 18:56
Hmmm... just tested it on another (which I should have done before posting... sorry) and it's working.

I do remember entering some details a month or two ago and it saved... but when I went to change them again today, it wouldn't save.

I did change the settings manually and it worked... 

The site won't display the custom invoice... uc-order--customer-bank_transfer.tpl.php  as well so something else is going on...

Thanks for looking, I'll do some more research and let you know my findings.

**Comment by argiepiano** [comment] 2022-11-21 18:58
Thanks. Question: you say 'a month or two ago', but this module was ported last week. Perhaps you are dealing with a D7 upgraded site that used this, and the issue is with the upgrade hook?

**Comment by albanycomputers** [comment] 2022-11-21 19:07
DOH!!!  Just realised... I converted it at the beginning of October... lol...  I don't know if I'm coming or going lol....

I thought it was a bit strange when I saw the date was last week lol :-)

Really sorry...  

![image](https://user-images.githubusercontent.com/1705388/203138889-eb4d5186-fa1e-4db2-a2ed-c603c270a226.png)

I think I need a holiday...  no, I know I need a holiday :)

**Comment by djzwerg** [comment] 2022-12-19 22:41
For me the bank details are getting saved but the custom invoice won't be displayed. I think this is an issue.

**Comment by argiepiano** [comment] 2022-12-19 22:50
@djzwerg, can you please post steps to reproduce the problem?

**Comment by argiepiano** [comment] 2022-12-19 22:51
And please open a separate issue. I'm going to close this as "works as designed" since @albanycomputers found out it was another problem unrelated to the module.

**Closed as completed** 2022-12-19 22:51 UTC
Labels: status - works as designed

**Comment by djzwerg** [comment] 2022-12-20 13:05
@argiepiano ok I'm going to do this later.
